### ISSUE TITLE
Concerns about the CEL-seq data

### ISSUE THREAD

**Issue by jonbra** [caseywdunn/levin2016#2]
Hi, thank you for putting all this on the GitHub. Very interesting to read!

I was wondering if you have also considered the possible impact of bias in both gene expression estimates and gene drop-out (missing genes due to low RNA input) arising from the CEL-seq method? If I understand correctly, CEL-seq does not apply Unique Molecular Identifiers (UMIs) to obtain absolute gene expression counts, and all such single cell methods may have huge bias in gene expression and in the number of genes detected. Even though Levin et al. used the BLIND approach to compute gene expression, this might still be heavily influenced by these biases, and thereby also the results?

Thank you,

Jon

**Comment by caseywdunn** [comment]
I didn't address that part of the analysis here, but I agree that comparing counts across species in the way presented here is problematic. See http://dx.doi.org/10.1093/icb/ict068 for a further explanation of why ratios of counts, not counts themselves, should be compared across species. UMI's are a step in the right direction, but they account for only one of the sources of technical bias - amplification. There are still other biases, including reverse transcription and sequencing, that remain to be accounted for. There are ways to correct for these biases (outlined in the link) without knowing exactly what they all are since they uniformly apply within each species.

**Comment by jonbra** [comment]
Great! Thanks for your feedback!
